### PR TITLE
Vulkan support

### PR DESCRIPTION
**Pull request by mosra**
Hi @ginkgo!

I was very happy with how flextGL GL and GLES loading worked for me in [Magnum](https://github.com/mosra/magnum), so I wanted to continue using it for Vulkan as well. Fortunately the `vk.xml` has a lot in common ẃith `gl.xml` so I didn't need to rewrite the whole thing.

## How it looks

```txt
version 1.1 vulkan

# Extensions to use, in addition to the core version
extension KHR_swapchain optional

# Optional function whitelist. If you don't specify anything, everything gets
# pulled in.
begin functions
    CreateInstance
    CreateBuffer
    CmdDraw
    CreateSwapchainKHR
end functions

# You can also say `begin functions blacklist` for a blacklist
```

## What's done

First of all I created a bunch of tests to have 100% code coverage, to ensure that none of the current GL parsing got broken on the way and the templates still produce the same output. I tried to make the test cases as minimal as possible, but the expected output files are still quite big. However I think the pros of having everything tested outweigh the increased size of the repository.

The test is built with the usual `python.unittest` and supports code coverage as well. A minimal HOWTO is in `test/__init__.py`:

```sh
cd flextGL
python -m unittest # to run tests w/o coverage

coverage run -m unittest # to run tests w/ coverage
coverage html -i # and then open htmlcov/index.html for the full report
```

Since Vulkan relies a lot on various struct and enum definitions, I extended the function whitelist / blacklist features to also include just types that are actually referenced by functions and not including those that are not needed. That affects GL as well, for example the `GLsync` type is not included if the `glWaitSync()` function is blacklisted. I went some extra steps to ensure that even types of enabled extensions that are referenced indirectly via `pNext` pointers are properly included.

Compared to GL, Vulkan has a different approach to promoting extensions to core -- instead of adding another enum with a different name and the same value, the extension name becomes an alias to the core name. That's the same with preprocessor defines. Extension types become `typedef`s to the core types, only commands are present twice, once with the extension suffix, once without. That's consistent with what the `vulkan_core.h` header is doing. Some examples of what I mean:

```cpp
#define VK_QUEUE_FAMILY_EXTERNAL (~0U-1)
#define VK_QUEUE_FAMILY_EXTERNAL_KHR VK_QUEUE_FAMILY_EXTERNAL

// ...

typedef enum {
    // ...
    VK_ERROR_OUT_OF_POOL_MEMORY = -1000069000,
    VK_ERROR_OUT_OF_POOL_MEMORY_KHR = VK_ERROR_OUT_OF_POOL_MEMORY
} VkResult;

// ...

typedef struct {
    VkStructureType sType;
    const void*                     pNext;
    uint32_t                        aspectReferenceCount;
    const VkInputAttachmentAspectReference* pAspectReferences;
} VkRenderPassInputAttachmentAspectCreateInfo;

typedef VkRenderPassInputAttachmentAspectCreateInfo VkRenderPassInputAttachmentAspectCreateInfoKHR;
```

There's now a basic `vulkan` template, which just loads pointers globally (the simplest way). The README describes a basic usage of it. By creating a special template tt's also possible to load instance- and device-specific pointers (like [Volk](https://github.com/zeux/volk) does, for example), but it's non-trivial from the user perspective, so the default template doesn't do that. One of the test cases loads instance-specific pointers, though.

## Possible future steps

This is a first version and I'm not going to pretend it's completely bug-free, so I might bother you with further patches in the future. Besides that, what I can do as well:

-   Building this project on Travis CI to prevent accidental breakages when new versions of `vk.xml` get released or when the code gets updated. **I can help you with setting it up for your account.**
-   Switching to the Jinja2 templating engine instead of Wheezy -- it's basically ubiquitous (packages for it are in all distros) and doesn't have weird quirks like having to insert a newline to escape `(` characters. I think it could be also possible to support both, *somehow*.
-   There's a bunch of trailing whitespace and inconsistent naming style throughout the code. I tried to preserve the original state to avoid noise in the diff, but I think it would make sense to clean these things up. 

Opinions (encouragement/discouragement) on the above very welcome!

## Reviewing the PR

I encourage going commit-by-commit when reviewing, everything at once makes less sense than the individual commits.

## Future maintenance of flextGL

*Most importantly:* since I have a project that completely relies on flextGL, **I'm offering to take over the maintenance** of it, in case you don't have time or resources to work on it or simply moved on to other things. I'm also completely fine with just submitting pull-requests as I was doing until now ;)

### CODE REVIEW

**Comment by ginkgo** [comment]
Hi @mosra,

sorry I can't get back to you sooner, but I'm kind of busy this week. (I'm moving) 

I'll have a look over your changes later. Transferring maintainership of the project to you might be an option.

**Comment by mosra** [comment]
Sure, no problem :)

**Comment by ginkgo** [comment]
I skimmed over the changes and they look good overall.  It is a pretty big change though so it's a bit hard for me to tell if everything's alright. The GL regression tests are reassuring though.

Regarding maintainership: I think this would make a lot of sense. Judging from git blame you'll be responsible for most of the code after this change anyways.
flextGL is MIT licensed so you're always free to just fork it and maintain your own version under mosra/flextGL. If you rather want to maintain it under this URL then I can set you up as a collaborator here.

Regarding the possible future steps:
Continuous integration might be a good thing to add, since we now have proper testing.
I actually switched the template engine for this once before. I was using CheetahTemplate in the beginning and switched when moving to Python 3. I'm not particularly against switching templates again, but then again I can't think of any major reasons other than maybe Jinja being a bit more elegant.
Regarding style/whitespace inconsistencies: It might be useful to look out for a python code formatter and just autoformat everything.

**Comment by mosra** [comment]
> If you rather want to maintain it under this URL then I can set you up as a collaborator here.

Some possibilities:

- I keep maintaining my own fork, while this repository inevitably gets stale / out of sync with my fork and that could be bad for project discovery (when people find this repository and discover it was not updated in a while, they'll dismiss the whole project as being dead).
- You'll set me up as a collaborator and I'll maintain the project under this URL. However, you'll still be getting notifications about issues / PRs and I might ask you from time to time to update various settings on the CIs (because as an owner you're the only person who can do it), so it still imposes some burden on you.
- Another possibility could be to [transfer the repository](https://help.github.com/articles/about-repository-transfers/) to my account. That would basically swap our roles, I become the owner, you'll be a collaborator and all links pointing to ginkgo/flextGL will redirect to mosra/flextGL. However, this feels a bit like stealing and I'm not sure if you'd be okay with that ;)

> I can't think of any major reasons other than maybe Jinja being a bit more elegant

Sure, Wheezy Template works at the moment, the only problem is that not all distributions have it in their system packages and (at least in my opinion) Jinja is more well known among developers, so using it could lower the bar for 3rd party contributions.

> It might be useful to look out for a python code formatter and just autoformat everything.

I could set up a pep8 / flake8 tests on the CI to achieve that.

Regarding any possible future steps: my plan is to work on them later, after this PR is integrated, to avoid the PR becoming one of those huge neverending things (it's big enough already) :)

**Comment by ginkgo** [comment]
When trying to transfer ownership I get an error message saying that "mosra/flextGL already exists".
Which makes sense I guess, although I don't understand what's the point of ownership transfer then.

I'll make you a collaborator for now.

**Comment by mosra** [comment]
Yeah, sorry, forgot to mention, I would need to rename (and later delete) that repository for the transfer to work, but this PR should be merged first to avoid getting lost.

Thanks for making me a collaborator! That means I *can* merge this myself now, the question is: should I? :)

**Comment by mosra** [comment]
@ginkgo Thank you! 

I renamed my fork and you should be hopefully able to transfer the ownership now. If not, I'll delete the fork altogether and then it should be *definitely* possible.

**Comment by ginkgo** [comment]
Hi @mosra, seems like just renaming the repo isn't enough:
>  mosra already has a repository in the ginkgo/flextGL network

**Comment by mosra** [comment]
Deleted it now. :)

**Comment by ginkgo** [comment]
It's waiting for you to approve the transfer. :)

**Comment by mosra** [comment]
Argh, sorry, for some reason it landed in a spam inbox and I wasn't fast enough to discover it in time :(

Can you initiate the transfer again, please?

**Comment by mosra** [comment]
@ginkgo Got it, finally. Thanks for your patience and sorry for all the problems :)

**Pull request merged**
