### PR TITLE
Nedded functions option and another template

### PR DESCRIPTION
**Pull request by eternalrain**
-F <filename> option to pass list of GL funcs that need to be loaded.
'lite' template - same as 'compatible' but produses smaller binary (and bunch of warnings).
Tested on win32 mingw.

### CODE REVIEW

**Comment by ginkgo** [comment]
Hello eternalrain,
I agree that an explicit whitelist of functions to load is a useful feature to have.  Although it might be better to add this as a new command/construct to the profile files, so that you can write something like this:

```
begin functions
glEnable glDisable
glClear glClearDepth glClearColor 
glBegin glEnd
end functions
```
Would this work for you? I can look into adding that..

I didn't have too much time yet to look into your lite template. What are the major changes you did there? Maybe the warnings can be supressed with pragmas.

**Comment by eternalrain** [comment]
Honestly, my first thought was to implement it like this, but i just didnt want to mess with a profile parsing code, so i'm totally ok if you make it this way.

As for template, i define a struct with func ptrs, statically initialize it with corresponding names and on loader function iterate over it like it was array of ptrs:  vp[i] = get_proc(vp[i]).
Just checked: wrapping struct into union with void* array gets rid of warnings. I'll make a change in template in a while.

**Comment by ginkgo** [comment]
I've merged your changes now. The function list can now be defined in the profile.

You can find an example of this in the flextGL-example project: https://github.com/ginkgo/flextGL-example

**Comment by eternalrain** [comment]
ok, thanks

**Pull request merged**
